### PR TITLE
beaker: migrate to f41

### LINKED ISSUE #3462: beaker: f41+ containers can't start tests
First steps for migration were done in #3463

copr-dev hasn't f41 chroot enabled, thus beaker inside f41 fails:

```
Something went wrong:
Error: chroots: 'fedora-41-x86_64' is not a valid choice for this field.
:: [ 10:09:11 ] :: [   FAIL   ] :: Command 'copr-cli create --chroot fedora-41-x86_64 --disable_createrepo false @copr/TEST1728295748689287368DisableCreaterepoFalse' (Expected 0, got 1)
```

the same is expected for internal copr. Idk what is needed next to make tests work, but I am 100% sure module tests will be broken.

### PR DESCRIPTION
**Pull request by nikromen**
Fixes #3462

### CODE REVIEW

File: beaker-tests/DockerTestEnv/Makefile [hunk 1]
```diff
@@ -13,7 +13,7 @@ bld: build
 run:
 	$(CONTAINER_ENGINE) run \
 		-dit \
-		-v $(mkfile_path)/../..:/root/copr \
+		-v $(mkfile_path)/../..:/root/copr:Z \
```
Comment (FrostyX) [inline beaker-tests/DockerTestEnv/Makefile:16]: Would `:z` work too? I generally try to avoid `:Z` because the bindmount cannot be accessed from other containers. Shouldn't be a problem here but still

Comment (nikromen) [reply beaker-tests/DockerTestEnv/Makefile:16]: That was the reason why I put `:Z` here to pretend at least I care about minimal privileges since I know we don't want to access the bind-mount from other containers. But yeah, it doesn;t mater in this use case so `:z` would work too.

File: beaker-tests/DockerTestEnv/Dockerfile [hunk 2]
```diff
@@ -7,15 +7,15 @@ RUN dnf -y update \
     && dnf -y install dnf-plugins-core wget \
     && dnf -y copr enable @copr/copr \
     && if test "$COPR_PACKAGES" = devel; then dnf -y copr enable @copr/copr-dev; fi \
-    && dnf -y install hostname htop net-tools iputils vim mlocate git sudo \
+    && dnf -y install hostname htop net-tools iputils vim plocate git sudo \
```
Comment (nikromen) [inline beaker-tests/DockerTestEnv/Dockerfile:10]: do we need plocate?

**Comment by FrostyX** [comment]
Is there any other blocker or only the `:z` and `plocate` things needs to be addressed?

File: beaker-tests/Sanity/copr-cli-basic-operations/runtest-modules.sh [hunk 3]
```diff
@@ -99,6 +99,7 @@ rlJournalStart
 
         # Test yaml submit
         PROJECT=module-testmodule-beakertest-$DATE
+        echo "copr-cli create $PROJECT --chroot $CHROOT --chroot fedora-rawhide-i386"
```
Comment (FrostyX) [inline beaker-tests/Sanity/copr-cli-basic-operations/runtest-modules.sh:102]: This seems to be a leftover from debugging

File: beaker-tests/Sanity/copr-cli-basic-operations/runtest-modules.sh [hunk 4]
```diff
@@ -85,7 +85,7 @@ function test_successful_packages()
 rlJournalStart
     rlPhaseStartSetup
         setup_checks
-        yum -y install dnf dnf-plugins-core
+        yum -y install dnf dnf-3 dnf-plugins-core
```
Comment (praiskup) [inline beaker-tests/Sanity/copr-cli-basic-operations/runtest-modules.sh:88]: I never seen `dnf-3` :D interesting.

Having `dnf install dnf4 dnf3` would be slightly more obvios.

File: beaker-tests/Sanity/copr-cli-basic-operations/runtest-dnf-copr.sh [hunk 5]
```diff
@@ -46,24 +46,26 @@ rlJournalStart
...
         rlRun "dnf -y copr enable --hub tested-copr ${NAME_PREFIX}DnfCopr"
         rlRun "dnf -y install hello"
         rlRun "hello"
-        rlRun "dnf -y erase hello"
+        rlRun "dnf -y remove hello"
 
         # Test `dnf copr list --available-by-user' command
-        rlRun "dnf copr --hub tested-copr list --available-by-user $OWNER > $OUTPUT"
+        # TODO Implement the --available-by-user' parameter in DNF5
+        rlRun "dnf-3 copr --hub tested-copr list --available-by-user $OWNER > $OUTPUT"
```
Comment (praiskup) [inline beaker-tests/Sanity/copr-cli-basic-operations/runtest-dnf-copr.sh:68]: Do we really need that?  I never used this.

Comment (praiskup) [reply beaker-tests/Sanity/copr-cli-basic-operations/runtest-dnf-copr.sh:68]: I mean, "do we need to implement this in DNF5?"

File: beaker-tests/Sanity/copr-cli-basic-operations/runtest-dnf-copr.sh [hunk 6]
```diff
@@ -46,24 +46,26 @@ rlJournalStart
         OUTPUT=`mktemp`
 
         # Test `dnf copr search' command
+        # TODO Implement the search command in DNF5
```
Comment (praiskup) [inline beaker-tests/Sanity/copr-cli-basic-operations/runtest-dnf-copr.sh:49]: Again, do we need this in DNF5? If yes, open an issue, if not - let's just leave it with comment that we don't plan to implement it.

Comment (FrostyX) [reply beaker-tests/Sanity/copr-cli-basic-operations/runtest-dnf-copr.sh:49]: I don't know if we necessarily need it, but in comparison to the not-very-useful `--available-by-user` parameter, the search command could be nice to have. I will create a ticket for that. Do you prefer it in the DNF or Copr issue tracker?

File: beaker-tests/Sanity/copr-cli-basic-operations/runtest-modules.sh (hunk 4 above)
Comment (nikromen) [reply beaker-tests/Sanity/copr-cli-basic-operations/runtest-modules.sh:88]: on fedora 41:

```
[root@10a47da1ac97 /]# dnf install dnf3
Updating and loading repositories:
Repositories loaded.
Failed to resolve the transaction:
No match for argument: dnf3
You can try to add to command line:
  --skip-unavailable to skip unavailable packages
[root@10a47da1ac97 /]#
```

Comment (nikromen) [reply beaker-tests/Sanity/copr-cli-basic-operations/runtest-modules.sh:88]: s/dnf-3/dnf4

**Comment by nikromen** [comment]
I pushed some fixes, the tests passes for modules and I started all tests against dev, but I think with some changes in the main branch - some of them will probably fail unrelated to this. @FrostyX you tried to fix some problems not related to modules but still related to dnf4, do you think that your changes are enough then?

And I also left the TODOs as they are for you to decide whether to drop them or create issue about them - I don't have strong opinion on that.

**Comment by FrostyX** [comment]
I updated the TODOs, and I am going to merge now. Anything else can be done in a follow-up PR.
